name: laundry_bin
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: 
  flutter_localization: ^0.2.1
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0+3
  animated_notch_bottom_bar: ^1.0.0
  flutter_hooks: ^0.20.5
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  coupon_uikit: ^0.2.1
  lottie: ^3.1.2
  objectbox: ^4.0.1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  cloud_firestore: ^5.2.0
  intl_phone_field: ^3.2.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.3
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  json_annotation: ^4.9.0
  hooks_riverpod: ^2.5.1
  google_maps_flutter: ^2.9.0
  otp_text_field: ^1.1.3
  google_sign_in: ^6.2.1
  firebase_storage: ^12.1.3
  file_picker: ^8.0.6
  get_storage: ^2.1.1
  geocoding: ^3.0.0
  flutter_typeahead: ^5.2.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  geolocator: ^12.0.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  json_serializable: ^6.8.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/DMSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DMSans-Black.ttf
          weight: 900
